name: PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VITE_BASE_URL: ${{ vars.VITE_BASE_URL }}/pr-preview/pr-${{ github.event.pull_request.number}}
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
      VITE_APP_AUTH_BASE_URL: ${{ vars.VITE_APP_AUTH_BASE_URL }}
      VITE_APP_REFRESH_AUTH_BASE_URL: ${{ vars.VITE_APP_REFRESH_AUTH_BASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      - name: Install and Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy-preview:
    name: Deploy preview
    needs: build
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist
          umbrella-dir: pr-preview
